Update to bitvec 0.22
zkcrypto/jubjub pull request #44
Opened 2021-05-19 23:22 UTC by nuttycom

2021-05-20 23:32 UTC, str4d commented on Cargo.toml
> +bls12_381 = { git = "https://github.com/nuttycom/bls12_381.git", branch = "bitvec-0.22", default-features = false }
Once https://github.com/zkcrypto/bls12_381/pull/62 merges:
```suggestion
bls12_381 = { git = "https://github.com/zkcrypto/bls12_381.git", branch = "main", default-features = false }
```

2021-05-21 14:18 UTC, ebfull requested changes

2021-05-21 14:18 UTC, ebfull commented on src/lib.rs
> +    }
Are we sure this isn't recursing forever and nothing is calling it in our test suite? Might be better to do `ExtendedPoint::is_torsion_free(self)`.

2021-05-21 14:24 UTC, str4d commented on src/lib.rs
> +    }
It's a call to a concrete method inside a trait method, which rustc does know how to handle. The stack overflow issue we saw in the Zcash crates was due to two traits having the same method name.

2021-05-21 14:27 UTC, str4d commented on src/lib.rs
> +    }
From https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name:

> When we call `fly` on an instance of `Human`, the compiler defaults to calling the method that is directly implemented on the type
> [...]
> Specifying the trait name before the method name clarifies to Rust which implementation of `fly` we want to call. We could also write `Human::fly(&person)`, which is equivalent to the `person.fly()` that we used in Listing 19-18, but this is a bit longer to write if we don’t need to disambiguate.

2021-05-21 14:29 UTC, ebfull commented on src/lib.rs
> +    }
Okay, cool.

2021-05-21 14:29 UTC, ebfull approved these changes

2021-05-21 14:30 UTC, str4d commented on Cargo.toml
>  default = ["alloc"]
```suggestion
default = ["alloc", "bits"]
```

2021-05-21 14:42 UTC, merged